config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root "pages#home"
  get 'events/new_event_date', to: "events#new_event_date", as: :new_event_event_date_otf

  resources :events do
    resources :event_dates, shallow: true
    resources :comments, shallow: true
  end

  resource :user do
    resources :invitations, only: [:show, :index, :destroy], shallow: true
  end

  resource :pages

  resources :organizations do
    resources :members
  end


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    if person.present? and person.class.name == "User"
      can :manage, User, user_id: person.id
      can :manage, Invitation, user_id: person.id
      can :manage, Event, :all
    elsif person.present? and person.class.name == "Admin"
      can :manage, :all
    else
      can :read, Event
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable -- admins in the TicketShop are not registerable!
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization, optional: true
  has_many :event_dates
  has_many :comments
  has_one_attached :flayer
  accepts_nested_attributes_for :event_dates, allow_destroy: true

  validates :title, :description, presence: true
  validates :address, presence: true
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :event_date
  belongs_to :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:id, :username, :name, :biography, :location, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'card text-white bg-danger mb-3') do
        concat(content_tag(:div, class: 'card-header') do
          concat(content_tag(:h4) do
            concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: 'card-body') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end

  def current_person
    if current_user
      current_user
    elsif current_admin
      current_admin
    else
      User.new
    end
  end

  def invitations_count
    if cookies.has_key?("#{current_person.email}_invitations")
      invitations_count = JSON.parse(cookies["#{current_person.email}_invitations"])
      num_items = 0
      invitations_count.each_key do |k|
        num_items += invitations_count[k]
      end
      return num_items
    end
    return 0
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.erb
<div class="row ml-0">
  <%= form_with model: user, local: true do |form| %>
    <%= errors_for user %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :Biography %>
      <%= form.text_area :Biography, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :Location %>
      <%= form.text_field :Location %>
    </div>
    <div class="form-group">
      <%= form.label :Profile_picture %>
      <%= form.file_field :avatar, class: "form-control-file" %>
    </div>
    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/users/_user.erb
<% if user_signed_in? %>
  <div class="card mt-4">
    <div class="card-body">
      Welcome, <%= current_user.name %>
    </div>
    <div class="card-body">
      <%= link_to "Create Event", new_event_path, class: ["btn", "btn-primary"] %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit my profile</h1>

<%= render partial: 'form',
           locals: {
               user: @user,
               submit_btn_text: "Update"
           } %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row ml-0 mt-3">
  <h2><%= image_tag(@user.profile_picture.attached? ? @user.profile_picture.variant(resize_to_limit: [100, 100]) : "thumbnail.svg", width: "100px", data: { toggle: "modal", target: "#viewFlyer" }) %></h2>
</div>

<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <li><strong>Username:</strong> <%= @user.username %></li>
    <li><strong>Name:</strong> <%= @user.name %></li>
    <li><strong>Email:</strong> <%= @user.email %></li>
    <li><strong>Location:</strong> <%= @user.location %></li>
    <li><strong>Biography:</strong> <%= @user.biography %></li>
  </ul>
</div>

<%= link_to 'Edit', edit_user_path(@user) %>