config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root "pages#home"
  get 'events/new_event_date', to: "events#new_event_date", as: :new_event_event_date_otf

  resources :events do
    resources :event_dates, shallow: true
    resources :comments, shallow: true
  end

  resource :user do
    resources :invitations, only: [:show, :index, :destroy], shallow: true
  end

  resource :pages

  resources :organizations do
    resources :members
  end


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    if person.present? and person.class.name == "User"
      can :manage, User, user_id: person.id
      can :manage, Invitation, user_id: person.id
      can :manage, Event, :all
    elsif person.present? and person.class.name == "Admin"
      can :manage, :all
    else
      can :read, Event
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable -- admins in the TicketShop are not registerable!
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization, optional: true
  has_many :event_dates
  has_many :comments
  has_one_attached :flayer
  accepts_nested_attributes_for :event_dates, allow_destroy: true

  validates :title, :description, presence: true
  validates :address, presence: true
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :event_date
  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = Event.includes(:event_dates).all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.event_dates.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_event_date
    @event_date = EventDate.new
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:id, :title, :description, :address, :flayer,
                                      event_dates_attributes: [:id, :start_date, :end_date, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def errors_for(object)
    if object.errors.any?
      content_tag(:div, class: 'card text-white bg-danger mb-3') do
        concat(content_tag(:div, class: 'card-header') do
          concat(content_tag(:h4) do
            concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
          end)
        end)
        concat(content_tag(:div, class: 'card-body') do
          concat(content_tag(:ul) do
            object.errors.full_messages.each do |msg|
              concat content_tag(:li, msg)
            end
          end)
        end)
      end
    end
  end

  def current_person
    if current_user
      current_user
    elsif current_admin
      current_admin
    else
      User.new
    end
  end

  def invitations_count
    if cookies.has_key?("#{current_person.email}_invitations")
      invitations_count = JSON.parse(cookies["#{current_person.email}_invitations"])
      num_items = 0
      invitations_count.each_key do |k|
        num_items += invitations_count[k]
      end
      return num_items
    end
    return 0
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_event_date_form.erb
<div class="new-event-date-otf">
  <%= fields_for 'event[event_dates_attributes]', event_date, index: Time.now.utc.to_formatted_s(:number) do |event_date_form| %>
    <%= event_date_form.label :start_date %>
    <%= event_date_form.datetime_local_field :start_date, class: "form-control" %>
    <%= event_date_form.label :end_date %>
    <%= event_date_form.datetime_local_field :end_date, class: "form-control" %>
    <br>
    <button type="button" class="btn btn-danger remove-event-date-btn-otf">
      <i class="far fa-minus-square"></i>
    </button>
    <hr>
  <% end %>
</div>

app/views/events/_event_list.erb
<div class="row event-list">
  <% events.each do |event| %>
    <%= render partial: 'events/event_tile', locals: { event: event } %>
  <% end %>
</div>

app/views/events/_event_tile.erb
<div class="col-md-4" data-event-title="<%= event.title %>">
  <div class="card mb-4 shadow-sm">
    <%= link_to image_tag(event.flayer.attached? ? event.flayer.variant(resize_to_limit: [400, 300]) : "thumbnail.svg", class: "card-img-top", width: "100%", background: "#55595c", color: "#eceeef"), url_for(event) %>
    <div class="card-body">
      <p class="card-text"><%= link_to event.title, event %></p>
      <p class="card-text"><%= event.address %></p>
      <p class="card-text"><%= event.final_date %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "View", event %></button>
          <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Edit", edit_event_path(event) %></button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="row ml-0">
  <%= form_with model: event, local: true do |form| %>
    <%= errors_for event %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :flayer %>
      <%= form.file_field :flayer, class: "form-control-file" %>
    </div>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Event dates (pending)</h5>
        <p><%= event_date_instruction_text %></p>
        <%=form.fields_for :event_dates do |event_dates_form| %>
          <div id="event-dates-nested-forms" class="form-group">
            <%= event_dates_form.label :start_date %>
            <%= event_dates_form.datetime_local_field :start_date, class: "form-control" %>
            <%= event_dates_form.label :end_date %>
            <%= event_dates_form.datetime_local_field :end_date, class: "form-control" %>
            <% if action_name == 'edit' %>
              <%= event_dates_form.label "Delete"%>
              <%= event_dates_form.check_box :_destroy %>
            <% end %>
            <hr>
          </div>
        <% end %>
        <% if action_name == 'new' %>
          Add date link (pending)
          <!-- TODO: Add multiple dates -->
          <%= link_to "Add Date", root_path,
                     class: [ 'btn', 'btn-primary'], remote: true %>
          <!-- END TODO -->

        <% end %>
      </div>
    </div>
    <div class="form-group mt-2">
      <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
      <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="row ml-0 mt-3">
  <h2>Edit "<%=@event.title%>" Event</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to edit the "<%=@event.title%>" event:</p>
</div>
<%= render partial: "form",
           locals: {
               event: @event,
               submit_btn_text: "Update",
               event_date_section_title: "Edit event ticket types",
               event_date_instruction_text: "You may edit existing ticket types for your event"
           } %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<%= render partial: 'events/event_list', locals: { events: @events } %>

app/views/events/new.html.erb
<div class="row ml-0 mt-3">
  <h2>New Event</h2>
</div>
<div class="row ml-0 mt-2">
  <p>Please enter the required information to create a new Event:</p>
</div>
<%= render partial: "form",
           locals: {
               event: @event,
               submit_btn_text: "Create",
               event_date_section_title: "Add a ticket type",
               event_date_instruction_text: "You need to add an event date to your newly created event"
           } %>

app/views/events/show.html.erb
<div class="row ml-0 mt-3">
  <h2><%=@event.title %></h2>
</div>
<div class="row ml-0 mt-3">
  <h2><%= image_tag(@event.flayer.attached? ? @event.flayer.variant(resize_to_limit: [400, 300]) : "thumbnail.svg", width: "400px", data: { toggle: "modal", target: "#viewFlayer" }) %></h2>
</div>
<div class="row ml-0 mt-3">
  <ul class="list-unstyled">
    <li><strong>Description:</strong> <%=@event.description %></li>
    <li><strong>Address:</strong> <%=@event.address %></li>
  </ul>
</div>
<% if user_signed_in? %>
  <div class="row ml-0 mt-2 mb-3">
    Invite link (work in progress)
    &nbsp;
    <%= link_to "Edit Event", edit_event_path, class: ["btn", "btn-primary"] %>
  </div>
<% end %>
<div class="row ml-0 mt-3">
  <p><strong>Event dates:</strong></p>
  <table class="table">
    <thead>
    <tr>
      <th>Date</th>
      <th></th>
      <th>Participants</th>
    </tr>
    </thead>
    <tbody>
    <% @event.event_dates.each_with_index do |event_date, i| %>
      <tr>
        <td><%= event_date.start_date %></td>
        <td><%= event_date.end_date %></td>
        <td><%= event_date.subscribers %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="row ml-0 mt-3">
  <p><strong>Comments</strong></p>
  <table class="table">
    <thead>
    <tr>
      <th>Commenter</th>
      <th>Comment</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @event.comments.each do |comment| %>
      <tr>
        <td><%= comment.user.name %></td>
        <td><%= comment.body %></td>
        <td>report (pending)</td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <p>Add comment</p>
  <%= render 'comments/form' %>

</div>
<div class="row ml-0 mt-3 mb-3">
  <%= link_to 'Back', events_path, class: ['btn', 'btn-primary'] %>
</div>
<div class="modal" id="viewFlayer" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= @event.title %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag @event.flayer.attached? ? @event.flayer : "thumbnail.svg", width: "100%" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>