config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  root "pages#home"
  get 'events/new_event_date', to: "events#new_event_date", as: :new_event_event_date_otf

  resources :events do
    resources :event_dates, shallow: true
    resources :comments, shallow: true
  end

  resource :user do
    resources :invitations, only: [:show, :index, :destroy], shallow: true
  end

  resource :pages

  resources :organizations do
    resources :members
  end


end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(person)
    if person.present? and person.class.name == "User"
      can :manage, User, user_id: person.id
      can :manage, Invitation, user_id: person.id
      can :manage, Event, :all
    elsif person.present? and person.class.name == "Admin"
      can :manage, :all
    else
      can :read, Event
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :registerable -- admins in the TicketShop are not registerable!
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization, optional: true
  has_many :event_dates
  has_many :comments
  has_one_attached :flayer
  accepts_nested_attributes_for :event_dates, allow_destroy: true

  validates :title, :description, presence: true
  validates :address, presence: true
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture


end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :event_date
  belongs_to :user
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: ['btn', 'btn-primary'] %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: ['btn', 'btn-primary'] %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: ['btn', 'btn-secondary'] %> %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WT Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>

  <body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample03">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to "Events", events_path, class: "nav-link" %></li>
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Invitations", user_invitations_path, class: "nav-link" %></li>
            <li class="nav-item"> <%= link_to "My profile", @current_user, class: "nav-link" %> </li>
          <%end %>
        </ul>
        <span class="d-inline ml-3">
        <% if admin_signed_in? %>
        <%=link_to "Sign out", destroy_admin_session_path, method: :delete %>
        <% elsif !user_signed_in? %>
        <%=link_to "Sign in", new_user_session_path %> | <%=link_to "Sign up", new_user_registration_path %>
        <% elsif user_signed_in? %>
        <%=link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% end %>
        </span>
      </div>
    </nav>
  </header>
  <div class="container-fluid">
    <div class="row">
      <aside class="col-sm-2" id="customer_info">
        <% if user_signed_in? %>
          <%= render partial: "users/user", object: @current_user %>
        <% elsif admin_signed_in? %>
          <%= render partial: "admins/sessions/admin" %>
        <% end %>
      </aside>
      <main class="col-sm-10" id="main_content">
        <%= yield %>
      </main>
    </div>
  </div>
  <footer class="footer">
    <div class="container">
      <p class="float-right">
        <a href="#">Back to top</a>
      </p>
      <span class="text-muted">
        <p>About</p>
      </span>
    </div>
  </footer>
  </body>
</html>